#!/bin/bash

# Source default environment variables.
. $HOME/config/environment

# Start a gpg-agent instance.
gpg-connect-agent /bye

# Start an ssh-agent instance.
eval `ssh-agent`

# Merge X resources for the color theme.
xrdb -merge $HOME/config/xrdb/solarized.xrdb

# Start emacs as the window manager.
exec $HOME/bin/emacs --fullscreen
